### ISSUE TITLE
Vue3 Template issues

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/field-plugin#102]
# Vue3 Template issues

## Describe the bug
A collection of bugs with the vue3 template.

### To Reproduce
1. Run `npx @storyblok/field-plugin-cli@alpha --template vue3`
2. Run `cd ./nameoffieldtemplate`
3. Run `yarn dev`

#### [@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported."
![image](https://user-images.githubusercontent.com/5083273/228612287-41947429-e0b7-4303-ab14-2143cc7dd449.png)
Fix: Remove all explicit imports of `defineProps`.

#### Building with vue3 results in a non working field plugin where it infinite loads
![image](https://user-images.githubusercontent.com/5083273/228614945-20343f10-1eb7-4f75-ae48-a35f27b9c925.png)
No known fix.
**How to reproduce**
1. Follow the steps to reproduce above.
2. Run `yarn build`
3. Copy the `index.js` file.
4. Paste it into storyblok.
Additonal info about this issue:
![image](https://user-images.githubusercontent.com/5083273/228630410-a24a2043-82d9-46e5-9ef6-7ee96b6be13a.png)

**Comment by BibiSebi** [comment]
@SebbeJohansson thank you for raising this issues. 🙏 

We will inspect it and get back to you, once it is resolved!

**Comment by SebbeJohansson** [comment]
@BibiSebi Happy to help! As always, let me know if I can help!

**Comment by BibiSebi** [comment]
@SebbeJohansson new release has been published with the version [0.0.1-alpha.8](https://www.npmjs.com/package/@storyblok/field-plugin-cli/v/0.0.1-alpha.8) which fixes the issues inside this bug report. 

Please try it out and let us know if it worked for you.

**Comment by SebbeJohansson** [comment]
@BibiSebi That fixed that issue, but im still having issue.
Ill open a separate issue with the new issue.
