### ISSUE TITLE
Visual Editor does not detect changes in custom field plugin

### ISSUE THREAD

**Issue by RoettingerJ** [storyblok/field-plugin#336]
**Describe the bug**
I have following behavior with my custom field plugin:
The Visual Editor does not detect changes if the content of the field plugin changes

Created a react field plugin that returns an object like {A:stringA, b:stringB}.

In the plugin the state will be stored with useState
```
const [value, setValue] = useState<>({A: '',B: ''})
```
every time the value changes the setContent function will be called via an useEffect
```
  useEffect(() => {
    actions?.setContent(value)
  }, [value])
```

**To Reproduce**
1. Create a blok with a custom field plugin
2. Add the blok to a story
3. Change a value in the field plugin
4. "Save" button keeps state - signaling that there is no change

**Expected behavior**
"Save" button of Visual Editor should change to a different state - signaling that there are changes in the story

**Comment by demetriusfeijoo** [comment]
Hi @RoettingerJ 🙌 , thanks for reaching out to us 🤩 

Let me ask you something, if possible, would you mind recording a short video about this behavior?

**Comment by RoettingerJ** [comment]
Yes, please find attached video.
The save button "detects" changes in the field "Old Link" which is is a Storyblok default link field.
But if I change something in our plugin (field name "Link") the save button does change state.

https://github.com/storyblok/field-plugin/assets/83758340/f1ac68e9-1503-4ee4-9b4b-bba60f814f89

**Comment by RoettingerJ** [comment]
Yes, the value is in the JSON after hitting the `save` button

**Comment by demetriusfeijoo** [comment]
Perfect, thanks for confirming it, @RoettingerJ. 💯 

About the `Save` button state not being changed, I've already opened an internal ticket for that and as soon as it gets done, I come back to you. 🙌

**Comment by maximilian-schwarz** [comment]
Have currently exact the same issue like @RoettingerJ
