### ISSUE TITLE
Cannot find module '@storyblok/field-plugin/test' or its corresponding type declarations.

### ISSUE THREAD

**Issue by bemayr** [storyblok/field-plugin#343]
**Describe the bug**
I just bootstrapped a new custom field plug-in. When running `pnpm build` the task fails, because `@storyblok/field-plugin/test` could not be found.

**To Reproduce**
1. Run `pnpm dlx @storyblok/field-plugin-cli@latest create` with options **pnpm** and **vue3**.
2. Run `pnpm build`
3. The build task crashes with:

```
src/components/FieldPluginExample/index.spec.ts:4:34 - error TS2307: Cannot find module '@storyblok/field-plugin/test' or its corresponding type declarations.
```

**Expected behavior**
Bootstrapping an empty custom field works as described in the documentation.

**Screenshots**
I first discovered the problem after following the [guide regarding Continuous Delivery](https://www.storyblok.com/docs/plugins/field-plugins/continuous-delivery):
![image](https://github.com/storyblok/field-plugin/assets/6529243/8a86498d-9e97-4645-83e0-ed472059d729)
After doing some debugging I realized that I do not get auto-completion for the `test`-helpers package at all:
![image](https://github.com/storyblok/field-plugin/assets/6529243/0f983b05-a524-43be-bebd-37cf7ae5e3e9)
There is also no `test` folder in the distribution release:
![image](https://github.com/storyblok/field-plugin/assets/6529243/89202385-2757-4412-9d5b-126ea8026d0a)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.1.1 on Macbook Air 2020 M1
 - Node: 21.5.0
 - pnpm: 8.14.0
 - @storyblok/field-plugin: 1.0.1

**Additional context**
I did a bit of debugging into https://github.com/storyblok/field-plugin/blob/1e8889e7bfa5baae158509601fc9851e7e4a6877/packages/field-plugin/helpers/build.config.ts#L27-L36 and still wonder what's the difference between the `test`-package and the others?

**Comment by BibiSebi** [comment]
Hey @bemayer, thank you for the very detailed issue description, our team will investigate this and get back to you.

**Comment by BibiSebi** [comment]
Hey @bemayer, thank you for the very detailed issue description, our team will investigate this and get back to you.

**Comment by BibiSebi** [comment]
Hey @bemayr, good news, we fixed the issue. There are two ways you can do to make the build process work: 

1.  `pnpm dlx @storyblok/field-plugin-cli@latest create` you can run this command to create a new field plugin and everything should work
2. or feel free to update the field plugin dependency inside your project's package.json to `"@storyblok/field-plugin": "1.0.2"`

Let me know if you need any more assistance on this :)

**Comment by bemayr** [comment]
Thanks a lot @BibiSebi! I am glad I could help debugging and the issue was "simply" a missed release.
And thanks a lot for explaining the two ways on how to make the build process work, that's a service ;)

The build is working perfectly now, hence I'm closing this issue.
