### ISSUE TITLE
Add selected interface app language

### ISSUE THREAD

**Issue by maximilian-schwarz** [storyblok/field-plugin#344]
**Is your feature request related to a problem? Please describe.**
When I create a new field type plugin, I have no possibility to deliver e.g. texts, labels, descriptions, buttons in the language of the user, because I do not know the interface language of the user.

**Describe the solution you'd like**
Maybe add the storyblok interface language from the user to the message that the field type wrapper (parent) sends to the field type (child) via postMessage(). Now you can set the interface language in the Vue or React app and add the correct translations. If the language does not exist in the field plugin you can set a fallback.

**Comment by eunjae-lee** [comment]
Hi @maximilian-schwarz thanks for reporting this issue. I agree you should have both interface lang and story lang. We'll take a look internally and will let you know when we work on this feature :)

**Comment by maximilian-schwarz** [comment]
@eunjae-lee Glad to hear it. I'm really looking forward to the feedback after it has been discussed internally.
