### ISSUE TITLE
Field Plugin height is not correctly updated

### ISSUE THREAD

**Issue by BibiSebi** [storyblok/field-plugin#377]
**Describe the bug**
[Discord Link](https://discord.com/channels/700316478792138842/1194994065511551056/1216372316645232810)

**Expected behavior**
The field plugin size is adapted to its content and does not cut off parts of the iframe.

**Additional context**
storyblok/field-plugi@1.0.2 works correctly

**Comment by lukas-a-brand** [comment]
@BibiSebi 
Thanks for the update. 
**"@storyblok/field-plugin": "1.1.2"** seems to fix the problem with a new build & deploy of the plugin. (:
