### ISSUE TITLE
Extend CLI to enable deleting field-type plugins

### ISSUE THREAD

**Issue by edvinasjurele** [storyblok/field-plugin#382]
**Is your feature request related to a problem? Please describe.**

There is a way to publish (creates new or updates existing one), but there is no way to delete plugins via CLI, hence only via admin panel.

**Describe the solution you'd like**

Add possibility to delete plugin by name (or id (?), but name makes more sense as the publishing happens by stating the name) via CLI

**Comment by eunjae-lee** [comment]
Hi @edvinasjurele Thank you for raising this issue. Could you explain when you prefer deleting plugins using CLI instead of the admin panel?

**Comment by edvinasjurele** [comment]
Hi @eunjae-lee, it might not be strong argument for it, but we have been establishing the review flow of contributors pushing reviewable plugin version from MR via CI.

F.e. plugin is `my-plugin` and with a manual CI job contributor can push the plugin with name prefix of `-REVIEW-{MR_ID}`:
```
my-plugin-REVIEW-20
```

NOTE: We cannot use the original `my-plugin` as it first, meant for production, and second, there are only 2 states - draft and publish - per plugin instance, which is not scalable to work with multiple contributors at the same time, while risking accidentally publishing it for our content editors.

Also Organisation field-types can only be accessed by ADMINs, hence only admins can configure assigned spaces and delete plugins. We would like to finish review flow cycle to establish manual CI job for not only publishing a version, but also removing old plugin and leftovers.

**Comment by edvinasjurele** [comment]
More on the same note, we ended up in self-hosting the plugin `/dist` to our servers to enable us in testing plugins via sandbox `https://plugin-sandbox.storyblok.com/field-plugin?url={URL}`, but pushing plugin from MR branch is also an option, thus may be used not that frequently. Bugfixes or features can be checked in sandbox, but drastical reworks may need to be doublechecked in the wild :).

**Comment by eunjae-lee** [comment]
Thanks for sharing. What an interesting way to create a temporary plugin for testing. Then I understand why you'd want to delete leftovers. While we don't have that feature yet on the CLI, you could send a request to our [Management API](https://www.storyblok.com/docs/api/management#core-resources/field-types/delete-field-type) to achieve the same thing in the meantime.

**Comment by BibiSebi** [comment]
Hey @edvinasjurele, just wanted to let you know that I am starting to look into this request. I will give you updates once it is done 💯

**Comment by BibiSebi** [comment]
Hello @edvinasjurele ,

Apologies for the delayed update—I've been on sick leave this past week. After reviewing the implementation in more detail, I've encountered several blockers.

While deleting a field plugin itself is straightforward, the complexity increases when considering the impact on existing references. We would need to ensure users are fully aware of all references, especially if the plugin has been used across multiple stories or spaces. This would require changes to the MAPI, making the overall solution more complex than initially anticipated.

Given these considerations, we’ve decided not to move forward with this implementation. However, Eunjae previously shared a workaround that seems like a good fit for your case.

Thank you for your understanding!
