### ISSUE TITLE
"actions.selectAsset()" only returns the filename but not things like Alt Text or Asset ID

### ISSUE THREAD

**Issue by MilanFox** [storyblok/field-plugin#392]
**Describe the bug**
First of all, thanks for making Storyblok such a modular product.
The recent changes in the Field Plugins are much appreciated!

I am in need of building a rather customized version of the native asset selector, for which I would need the whole asset object, but "selectAsset()" only returns an Object that includes the filename for me, but not the rest of the Asset Metadata, like Alt Texts, Focus Points, etc.:

```json
{
  "filename": "https://www.a.storyblok.com/some/file/path.png"
}
```

I can reproduce the behaviour from a fresh new instance of a Plugin that is created with `"npx @storyblok/field-plugin-cli@latest add --dir \"./packages\" --structure monorepo"` (this is a monorepo project), so I am not linking a minimal repro here - in case this would help I am of course adding it.

I am using the Vue 3 template in case this makes a difference.

**To Reproduce**
1. Create a new Component, following [the documentation](https://www.storyblok.com/docs/plugins/field-plugins/create)
2. In the Example-Component "AssetSelector.vue", add a console log of the content of "asset.value" after line 10, where it waits for the asset selector promise.
3. Select any asset (in my case I've tried it with images only)
4. Console.log shows an "incomplete" asset object with only a filename.

**Expected behavior**
I would have expected the asset object to include the same data, that the native asset selector returns. At a minimum the asset ID so I can get the missing Info via the management API.

For reference, the Asset Object, I would have expected:
https://www.storyblok.com/docs/api/management/core-resources/assets/the-asset-object

**Desktop (Just in case this makes a difference):**
 - OS: OS X 14.5
 - Browser: Chrome 126.0.6478.114
 - Using @storyblok/field-plugin & @storyblok/field-plugin-cli @latest, which is currently 1.1.2, I think

**Additional context**
I did a very quick test with the old `<sb-asset-selector>` and I feel like this meta component does the same thing, but I might be wrong here.

**Comment by MilanFox** [comment]
I have decided to quickly set up a minimal repro anyways, just for convenience:

This Field Type Plugin:
```vue
<template>
  <SbButton size="small" @click="handleSelectAsset" is-full-width>Select Asset</SbButton>
  <SbButton size="small" @click="removeAsset" is-full-width>RemoveAsset</SbButton>
  <pre>{{ asset }}</pre>
</template>

<script setup lang="ts">
import { useFieldPlugin } from '@storyblok/field-plugin/vue3'
import { SbButton } from '@storyblok/design-system'
import { ref } from 'vue'

import type { Asset } from '@storyblok/field-plugin'

const asset = ref<Asset>()

const plugin = useFieldPlugin()

const handleSelectAsset = async () => {
  asset.value = await plugin?.actions?.selectAsset()
}

const removeAsset = () => {
  asset.value = undefined
}
</script>
```

produces this example output (I just printed it below the two buttons, sorry for the horrible formating)

![Bildschirmfoto 2024-06-24 um 18 13 54](https://github.com/storyblok/field-plugin/assets/31571437/0a5aa251-f783-4a8a-9842-ada28767c4c8)

**Comment by eunjae-lee** [comment]
Hi @MilanFox thanks for suggesting this change 🙂
As we are in the middle of something, I cannot guarantee the ETA, but I will hopefully discuss about this and bring it to you soon.

**Comment by MilanFox** [comment]
Hey thanks! Fully understandable - This would be much appreciated, but in the meantime, we are using a workaround through the Management API, so we are not in a hurry right now.

**Comment by eunjae-lee** [comment]
Hi @MilanFox , if you upgrade `@storyblok/field-plugin` to `1.2.0`, you will get the full object 🎉

```
await plugin.actions.selectAsset() // { "filename":  "", ... }
```
